trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  # provides pulumi access token + aws creds to runner env
  - group: cloud-secrets
  - name: YARN_CACHE_FOLDER
    value: $(Pipeline.Workspace)/.yarn
  # set for react-scripts test runner
  - name: CI
    value: true

stages:
  # Validation stage
  # Always runs first
  # Can run multiple validations (unit test, acceptance, linting) in parallel
- stage: Validation
  jobs:
    - job: ClientUnitTests
      steps:
      - task: Cache@2
        inputs:
          key: 'client | yarn | "$(Agent.OS)" | yarn.lock'
          path: $(YARN_CACHE_FOLDER)
        displayName: Cache Yarn packages

      - script: yarn install
        displayName: 'Install dependencies'

      - script: yarn test:unit
        displayName: 'Client Unit Tests'

      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testRunner: JUnit
          testResultsFiles: junit.xml

      - task: PublishCodeCoverageResults@1
        condition: succeededOrFailed()
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml

    - job: ClientUITests
      steps:
      - task: Cache@2
        inputs:
          key: 'client | yarn | "$(Agent.OS)" | yarn.lock'
          path: $(YARN_CACHE_FOLDER)
        displayName: Cache Yarn packages

      - script: yarn install
        displayName: 'Install dependencies'

      - script: yarn build
        displayName: 'Build test environment'

      - script: yarn test:ui
        displayName: 'Client UI Tests'

      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testRunner: JUnit
          testResultsFiles: junit.xml

      - task: PublishPipelineArtifact@1
        condition: failed()
        inputs:
          targetPath: 'test/ui/__image_snapshots__/__diff_output__'
          artifactName: UITestSnapshotDiff

    - job: PulumiValidation
      steps:
      - script: echo "TODO"
        displayName: 'Validate Pulumi code'

  # Pipeline publish stages
  # Depend on success of previous stage execution
- stage: PublishDev
  jobs:
    - template: pipeline-templates/build-and-deploy.template.yml
      parameters:
        environment: development
        artifactName: 'development-$(Build.SourceVersion)' # append the git hash to the artifact name

    - job: PostDeploy
      dependsOn:
        - Deploy
      steps:
      - script: echo "TODO"
        displayName: 'Some great regression tests'

  # only runs when run was triggered by git push
- stage: PublishQA
  condition: or(eq(variables['Build.Reason'], 'IndividualCI'), eq(variables['Build.Reason'], 'BatchedCI'))
  jobs:
    - template: pipeline-templates/build-and-deploy.template.yml
      parameters:
        environment: qa
        artifactName: 'qa-$(Build.SourceVersion)' # append the git hash to the artifact name

    - job: PostDeploy
      dependsOn:
        - Deploy
      steps:
      - script: echo "TODO"
        displayName: 'Some great integration tests'
