trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  # provides pulumi access token + aws creds to runner env
  - group: cloud-secrets
  - name: YARN_CACHE_FOLDER
    value: $(Pipeline.Workspace)/.yarn
  # set for react-scripts test runner
  - name: CI
    value: true

stages:
- stage: Validation
  jobs:
    - job: ClientUnitTests
      steps:
      - task: Cache@2
        inputs:
          key: 'client | yarn | "$(Agent.OS)" | yarn.lock'
          path: $(YARN_CACHE_FOLDER)
        displayName: Cache Yarn packages

      - script: |
          yarn install
          yarn test
        displayName: 'Client Unit Tests'

      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testRunner: JUnit
          testResultsFiles: junit.xml

      - task: PublishCodeCoverageResults@1
        condition: succeededOrFailed()
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml

    - job: PulumiValidation
      steps:
      - script: echo "TODO"
        displayName: 'Validate Pulumi code'

- stage: PublishDev
  variables:
    artifactName: 'Development-$(Build.SourceVersion)' # append the git hash to the artifact name
    environment: development
  jobs:
    - job: Artifact
      steps:
      - task: Cache@2
        inputs:
          key: 'client | yarn | "$(Agent.OS)" | yarn.lock'
          path: $(YARN_CACHE_FOLDER)
        displayName: Cache Yarn packages

      - script: |
          env | grep
          yarn install
          yarn build
        displayName: 'install and build'
        env:
          NODE_ENV: $(environment)

      - publish: dist
        artifact: $(artifactName)

    - job: Infrastructure
      steps:
      - task: Cache@2
        inputs:
          key: 'pulumi | yarn | "$(Agent.OS)" | yarn.lock'
          path: $(YARN_CACHE_FOLDER)
        displayName: Cache Yarn packages

      - script: yarn
        workingDirectory: 'infra/'
        displayName: 'install pulumi dependencies'

      - task: Pulumi@1
        condition: or(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.Reason'], 'Manual'))
        inputs:
          command: 'preview'
          cwd: 'infra/'
          stack: 'binhrobles/vue-nuxt-infra/$(environment)'

      - task: Pulumi@1
        condition: or(eq(variables['Build.Reason'], 'IndividualCI'), eq(variables['Build.Reason'], 'BatchedCI'))
        inputs:
          command: 'up'
          cwd: 'infra/'
          stack: 'binhrobles/vue-nuxt-infra/$(environment)'
          args: '--yes'

      - script: |
          echo "##vso[task.setvariable variable=bucketName;isOutput=true]$(pulumi stack output bucketName)"
        displayName: 'Set stack outputs as variables'
        workingDirectory: 'infra/'
        name: 'pulumi'

    - job: PublishApp
      dependsOn:
        - Artifact
        - Infrastructure

      # map in the variable
      # remember, expressions require single quotes
      variables:
        bucketName: $[ dependencies.Infrastructure.outputs['pulumi.bucketName'] ]

      steps:
      - download: current # specifies that artifact was published during this run
        artifact: $(artifactName)

      - task: AmazonWebServices.aws-vsts-tools.S3Upload.S3Upload@1
        displayName: 'S3 Upload: binhrobles-azurepipelines-test'
        inputs:
          regionName: 'us-west-2'
          bucketName: $(bucketName)
          sourceFolder: '$(Pipeline.Workspace)/$(artifactName)'
        env:  # explicitly map in secret env vars
          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
