# reusable template for artifacting and deploying a Vue Nuxt app
---
parameters:
- name: environment
  type: string
- name: artifactName
  type: string

jobs:
  - job: Artifact
    steps:
    - task: Cache@2
      inputs:
        key: 'client | yarn | "$(Agent.OS)" | yarn.lock'
        path: $(YARN_CACHE_FOLDER)
      displayName: Cache Yarn packages

    - script: yarn install
      displayName: 'Install dependencies'

    - script: |
        env | grep NODE_ENV
        yarn build
      displayName: 'Generate static resources'
      env:
        NODE_ENV: ${{ parameters.environment }}

    - publish: dist
      artifact: ${{ parameters.artifactName }}

  - job: Infrastructure
    steps:
    - task: Cache@2
      inputs:
        key: 'pulumi | yarn | "$(Agent.OS)" | yarn.lock'
        path: $(YARN_CACHE_FOLDER)
      displayName: Cache Yarn packages

    - script: yarn
      workingDirectory: 'infra/'
      displayName: 'install pulumi dependencies'

      # runs `pulumi preview` if PR or manual build invoked
    - task: Pulumi@1
      condition: or(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.Reason'], 'Manual'))
      inputs:
        command: 'preview'
        cwd: 'infra/'
        stack: 'binhrobles/vue-nuxt-infra/${{ parameters.environment }}'

      # runs `pulumi up --yes` if triggered by Git push
    - task: Pulumi@1
      condition: or(eq(variables['Build.Reason'], 'IndividualCI'), eq(variables['Build.Reason'], 'BatchedCI'))
      inputs:
        command: 'up'
        cwd: 'infra/'
        stack: 'binhrobles/vue-nuxt-infra/${{ parameters.environment }}'
        args: '--yes'

    - script: |
        echo "##vso[task.setvariable variable=bucketName;isOutput=true]$(pulumi stack output bucketName)"
      displayName: 'Set stack outputs as variables'
      workingDirectory: 'infra/'
      name: 'pulumi'

    # copies static files to s3 bucket after successful building and infra generation
    # only when triggered by Git push
  - job: Deploy
    condition: or(eq(variables['Build.Reason'], 'IndividualCI'), eq(variables['Build.Reason'], 'BatchedCI'))
    dependsOn:
      - Artifact
      - Infrastructure

    # map in the output from previous job
    # remember, expressions require single quotes
    variables:
      bucketName: $[ dependencies.Infrastructure.outputs['pulumi.bucketName'] ]

    steps:
    - download: current # specifies that artifact was published during this run
      artifact: ${{ parameters.artifactName }}

    - task: AmazonWebServices.aws-vsts-tools.S3Upload.S3Upload@1
      displayName: 'S3 Upload: ${{ parameters.artifactName }} to $(bucketName)'
      inputs:
        regionName: 'us-west-2'
        bucketName: $(bucketName)
        sourceFolder: '$(Pipeline.Workspace)/${{ parameters.artifactName }}'
      env:  # explicitly map in secret env vars
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
